default: &default
adapter: postgresql
encoding: unicode
pool: 5

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  database: golemtron_development
  username: golemtron_user
  password: password

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: golemtron_test
  pool: 5
  username: golemtron_user
  password: password

production:
  <<: *default
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: golemtron
  pool: 5
  username: <%= ENV['GOLEMTRON_DATABASE_USER'] %>
  password: <%= ENV['GOLEMTRON_DATABASE_PASSWORD'] %>
