# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )

Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )

Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )

Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )

Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )

Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Draft", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: true, submitted: false, published: false )




Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )

Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )

Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )

Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )

Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )

Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
Post.create(user_id: "1", title: "Lorem Ipsum : Submit", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec tincidunt massa, eu pulvinar sapien. Sed vulputate purus at metus aliquet, ac varius mi porta. In laoreet sodales nunc nec dictum. Quisque dapibus rutrum mollis. Cras vel purus id quam porttitor vulputate. Donec porttitor, arcu at lobortis dapibus, libero quam bibendum augue, vitae ornare nibh dolor non erat. Mauris quis sagittis massa. Mauris vitae massa sagittis, sodales arcu eu, dictum ipsum. Nulla et pulvinar lacus. ", is_drafted: false, submitted: true, published: false )
